#!/bin/bash
#
# Installation script for Raspberry Pi Rotary Encoder Driver
#
# This script compiles and installs the kernel module,
# sets up device permissions, and optionally configures
# the module to load at boot.
#
# Usage: sudo ./install.sh [options]
# Options:
#   --auto-load    Configure module to load automatically at boot
#   --help         Show this help message
#
# Author: Mark Mackelprang
# License: MIT

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
MODULE_NAME="rotary_encoder"
DEVICE_NAME="rotary_encoder"
UDEV_RULES_FILE="/etc/udev/rules.d/99-rotary-encoder.rules"
MODPROBE_CONF="/etc/modprobe.d/rotary-encoder.conf"
MODULES_LOAD="/etc/modules-load.d/rotary-encoder.conf"

# Function to print colored output
print_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
print_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
print_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
print_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Function to check if running as root
check_root() {
    if [[ $EUID -ne 0 ]]; then
        print_error "This script must be run as root (use sudo)"
        exit 1
    fi
}

# Function to check prerequisites
check_prerequisites() {
    print_info "Checking prerequisites..."
    
    # Check for kernel headers
    if [[ ! -d "/lib/modules/$(uname -r)/build" ]]; then
        print_error "Kernel headers not found. Install with:"
        print_error "  sudo apt update && sudo apt install raspberrypi-kernel-headers"
        exit 1
    fi
    
    # Check for build tools
    if ! command -v make &> /dev/null || ! command -v gcc &> /dev/null; then
        print_error "Build tools not found. Install with:"
        print_error "  sudo apt update && sudo apt install build-essential"
        exit 1
    fi
    
    print_success "Prerequisites check passed"
}

# Function to build the module
build_module() {
    print_info "Building kernel module..."
    
    if ! make clean; then
        print_error "Failed to clean previous build"
        exit 1
    fi
    
    if ! make; then
        print_error "Failed to build kernel module"
        exit 1
    fi
    
    print_success "Kernel module built successfully"
}

# Function to install the module
install_module() {
    print_info "Installing kernel module..."
    
    if ! make install; then
        print_error "Failed to install kernel module"
        exit 1
    fi
    
    # Update module dependencies
    depmod -a
    
    print_success "Kernel module installed"
}

# Function to create udev rules
create_udev_rules() {
    print_info "Creating udev rules..."
    
    cat > "$UDEV_RULES_FILE" << EOF
# Udev rules for Raspberry Pi Rotary Encoder Driver
# This file is automatically generated by the install script

# Set permissions for the rotary encoder device
KERNEL=="$DEVICE_NAME", MODE="0666", GROUP="input"

# Create symlinks for easier access
KERNEL=="$DEVICE_NAME", SYMLINK+="input/rotary_encoder"
EOF

    # Reload udev rules
    udevadm control --reload-rules
    udevadm trigger
    
    print_success "Udev rules created"
}

# Function to load the module
load_module() {
    print_info "Loading kernel module..."
    
    # Remove module if already loaded
    if lsmod | grep -q "^$MODULE_NAME "; then
        print_warning "Module already loaded, removing first..."
        rmmod "$MODULE_NAME" || true
    fi
    
    # Load the module with default parameters
    if ! modprobe "$MODULE_NAME"; then
        print_error "Failed to load kernel module"
        print_error "Check dmesg for error messages"
        exit 1
    fi
    
    # Wait a moment for device creation
    sleep 1
    
    # Check if device was created
    if [[ ! -c "/dev/$DEVICE_NAME" ]]; then
        print_error "Device file /dev/$DEVICE_NAME was not created"
        exit 1
    fi
    
    print_success "Kernel module loaded and device created"
}

# Function to configure auto-loading
configure_auto_load() {
    print_info "Configuring automatic module loading..."
    
    # Create modprobe configuration
    cat > "$MODPROBE_CONF" << EOF
# Configuration for Raspberry Pi Rotary Encoder Driver
# Uncomment and modify the options below as needed

# Default configuration (1 encoder on pins 18,19,20)
# options $MODULE_NAME num_encoders=1 clk_pins=18 dt_pins=19 sw_pins=20

# Example: 2 encoders, first with button, second without
# options $MODULE_NAME num_encoders=2 clk_pins=18,22 dt_pins=19,23 sw_pins=20,-1

# Example: 4 encoders, only first two with buttons
# options $MODULE_NAME num_encoders=4 clk_pins=18,22,24,26 dt_pins=19,23,25,27 sw_pins=20,21,-1,-1
EOF

    # Add module to modules-load.d
    echo "$MODULE_NAME" > "$MODULES_LOAD"
    
    print_success "Auto-loading configured"
    print_info "Edit $MODPROBE_CONF to customize GPIO pins"
}

# Function to build examples
build_examples() {
    print_info "Building example applications..."
    
    cd examples
    
    # Build C examples
    if gcc -o test_rotary ../test_rotary.c; then
        print_success "Built test_rotary"
    else
        print_warning "Failed to build test_rotary"
    fi
    
    if gcc -o volume_control volume_control.c; then
        print_success "Built volume_control"
    else
        print_warning "Failed to build volume_control"
    fi
    
    # Make Python example executable
    chmod +x rotary_encoder.py
    
    cd ..
    print_success "Example applications built"
}

# Function to show usage information
show_usage() {
    echo "Usage: sudo $0 [options]"
    echo ""
    echo "Options:"
    echo "  --auto-load    Configure module to load automatically at boot"
    echo "  --help         Show this help message"
    echo ""
    echo "This script will:"
    echo "  1. Check prerequisites (kernel headers, build tools)"
    echo "  2. Build the kernel module"
    echo "  3. Install the module to the system"
    echo "  4. Create udev rules for device permissions"
    echo "  5. Load the module and create device file"
    echo "  6. Build example applications"
    echo "  7. Optionally configure auto-loading at boot"
    echo ""
}

# Function to show post-install information
show_post_install() {
    print_success "Installation completed successfully!"
    echo ""
    print_info "Device file created: /dev/$DEVICE_NAME"
    print_info "Module loaded: $MODULE_NAME"
    echo ""
    print_info "Test the driver with:"
    print_info "  sudo ./test_rotary"
    print_info "  sudo ./examples/volume_control"
    print_info "  sudo python3 ./examples/rotary_encoder.py"
    echo ""
    print_info "Check module status with:"
    print_info "  lsmod | grep $MODULE_NAME"
    print_info "  dmesg | grep $MODULE_NAME"
    echo ""
    if [[ "$AUTO_LOAD" == "true" ]]; then
        print_info "Module configured for auto-loading at boot"
        print_info "Customize GPIO pins in: $MODPROBE_CONF"
    else
        print_info "To configure auto-loading at boot, run:"
        print_info "  sudo $0 --auto-load"
    fi
    echo ""
}

# Main installation function
main() {
    local AUTO_LOAD="false"
    
    # Parse command line arguments
    while [[ $# -gt 0 ]]; do
        case $1 in
            --auto-load)
                AUTO_LOAD="true"
                shift
                ;;
            --help)
                show_usage
                exit 0
                ;;
            *)
                print_error "Unknown option: $1"
                show_usage
                exit 1
                ;;
        esac
    done
    
    print_info "Raspberry Pi Rotary Encoder Driver Installation"
    echo "=============================================="
    
    check_root
    check_prerequisites
    build_module
    install_module
    create_udev_rules
    load_module
    build_examples
    
    if [[ "$AUTO_LOAD" == "true" ]]; then
        configure_auto_load
    fi
    
    show_post_install
}

# Run main function with all arguments
main "$@"